application: 'eicadallas'
runtime: java
version: '1'
inbound_services:
- warmup
derived_file_type:
- java_precompiled
threadsafe: True
api_version: '1.0'
handlers:
- url: (/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/.*/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: /add
  script: unused
  login: optional
  secure: optional
- url: /search
  script: unused
  login: optional
  secure: optional
- url: /
  script: unused
  login: optional
  secure: optional
- url: .*\.jsp
  script: unused
  login: optional
  secure: optional
- url: /.*/
  script: unused
  login: optional
  secure: optional
- url: /eica
  script: unused
  login: optional
  secure: optional
- url: /delete
  script: unused
  login: optional
  secure: optional
- url: /searchfordelete
  script: unused
  login: optional
  secure: optional
- url: /_ah/.*
  script: unused
  login: optional
  secure: optional
- url: /_ah/spi/.*
  script: unused
  login: optional
  secure: optional
